name: Mirror to GitLab and Codeberg

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: qte77/gha-github-mirror-action@main
        with:
          source_repo: https://github.com/Xxx91n/env-manager.git
          codeberg_url: 'https://codeberg.org/${{ vars.CODEBERG_USER }}/env-manager.git'
          codeberg_pat: ${{ secrets.CODEBERG_TOKEN }}

  gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: qte77/gha-github-mirror-action@main
        with:
          source_repo: https://github.com/Xxx91n/env-manager.git
          gitlab_url: 'https://gitlab.com/${{ vars.GITLAB_USER }}/env-manager.git'
          gitlab_pat: ${{ secrets.GITLAB_TOKEN }}
